balena-io-modules/odata-parser

- odata-parser.js
- odata-parser.ometajs
- package.json
- test/resource_parsing.coffee
Change-type: patch
Signed-off-by: Pagan Gazzard <page@resin.io>
> Correctly fail on empty options that are invalid

- README.md
- package.json
Fixes #28
Change-type: patch
Signed-off-by: Lucian <lucian.buzzo@gmail.com>
> Update README npm badge and change github links to balena-io-modules

- odata-parser.pegjs
> Fix adding parameter alias to the options object

- .circleci/config.yml
- .lintstagedrc
- odata-parser.d.ts
- package.json
> Add typings

- odata-parser.d.ts
> Improve typings

- odata-parser.pegjs
> Support `;` for separating expand options

- odata-parser.pegjs
- test/resource_parsing.coffee
> Accept trailing `?` with no query parameters

- odata-parser.pegjs
- test/resource_parsing.coffee
> Accept `+` in place of ` `/`%20` as some tools encode spaces that way

- odata-parser.d.ts
- odata-parser.pegjs
- package.json
- test/filterby.coffee
Change-type: minor
Implements #43
> Add support for `/$count` in filters

- .circleci/config.yml
- README.md
- package.json
* Drop support for nodejs 8
* Update to @balena/lint 5.x
* Rename to @balena/odata-parser
> 2.x major version

- odata-parser.d.ts
- odata-parser.pegjs
- test/resource_parsing.coffee
https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360936
Change-type: minor
> Add support for specifying named keys

- odata-parser.d.ts
- odata-parser.pegjs
- package.json
- test/format.coffee
> Add support for metadata argument in $format

- odata-parser.pegjs
- package.json
> Optimize number parsing

- odata-parser.pegjs
> Optimize `QuotedText` for the common case of few/no apostrophes

- tsconfig.json
> Remove some typescript strict mode exceptions

- odata-parser.pegjs
> Use shorthand object notation

- odata-parser.pegjs
- package.json
> Update to peggy 3 and make us of the repetition operator

- odata-parser.pegjs
- package.json
- tsconfig.json
> Proposal: v3

- .github/workflows/flowzone.yml
> Allow running CI on external PRs

- odata-parser.pegjs
> Optimize by moving constant values into global init

- odata-parser.d.ts
- tsconfig.json
> Fix type checking of the declaration file

- odata-parser.pegjs
- test/paging.js
> Use bind vars for $top and $skip options

- odata-parser.d.ts
Change-type: patch
See: https://github.com/balena-io-modules/odata-parser/pull/96
See: https://balena.fibery.io/Work/Project/Shape--Build-Add-support-for-sorting-on-user-selected-tag-columns-in-the-server-side-paginated-devic-912
> Add the missing properties in the PropertyPath typings

- package.json
- test/encoding.js
- test/resource_parsing.js
- tsconfig.json
> Build: switch tsconfig to use module "Node16" with type "commonjs"
